export const COMMON_COMMANDS = [
  // --- Essential Server Info ---
  'status',
  'stats',
  'tv_status',
  'meta list',
  'meta version',
  'css_plugins list',

  // --- CS2-SimpleAdmin (Plugin Commands) ---
  'css_who ',
  'css_players',
  'css_ban ',
  'css_addban ',
  'css_banip ',
  'css_unban ',
  'css_kick ',
  'css_gag ',
  'css_addgag ',
  'css_unmute ',
  'css_mute ',
  'css_addmute ',
  'css_give ',
  'css_strip ',
  'css_hp ',
  'css_speed ',
  'css_gravity ',
  'css_money ',
  'css_god ',
  'css_slay ',
  'css_slap ',
  'css_vote ',
  'css_map ',
  'css_wsmap ',
  'css_asay ',
  'css_say ',
  'css_psay ',
  'css_csay ',
  'css_hsay ',
  'css_noclip ',
  'css_freeze ',
  'css_unfreeze ',
  'css_respawn ',
  'css_cvar ',
  'css_rcon ',

  // --- Map & Match Control ---
  'map ',
  'changelevel ',
  'host_workshop_map ',
  'mp_restartgame 1',
  'mp_warmup_start',
  'mp_warmup_end',
  'mp_pause_match',
  'mp_unpause_match',
  'mp_roundtime ',
  'mp_freezetime ',
  'mp_maxrounds ',
  'mp_halftime ',
  'mp_c4timer ',

  // --- Bot Management ---
  'bot_add',
  'bot_kick',
  'bot_quota ',
  'bot_difficulty ',
  'bot_stop ',

  // --- Core Server Settings ---
  'sv_cheats ',
  'sv_gravity ',
  'sv_infinite_ammo ',
  'sv_alltalk ',
  'sv_full_alltalk ',
  'sv_password ',
  'hostname ',
  'sv_maxplayers ',
  'sv_lan ',

  // --- Plugin Management ---
  'meta refresh',
  'css_plugins reload ',
  'css_plugins load ',
  'css_plugins unload ',
  'exec ',
].sort();
